### PR TITLE
Select and display two random student photos

### PR DESCRIPTION
**Pull request by alstdu**
- Added a query to fetch two random non-null, non-empty photos from the 'students' table
- Included reference to a relevant article for potential optimization methods
- Display the selected photos in the HTML output

### CODE REVIEW

**Review by manhellis — CHANGES_REQUESTED** [review]
i thought you were going to create the graphic component in the figma file as well as the select feature.

**Comment by alstdu** [comment]
Oops, sorry I thought I was just writing the functionality! I can style it though

**Comment by alstdu** [comment]
Added styling for larger screens, let me know if this is what you want and then I can make it responsive

**Comment by alstdu** [comment]
If you want to merge what's here so far you can! 
Desktop screen sizes tested. 
- Nothing breaks on desktop unless your monitor is only 500px in height. 

Tablet Tested.
- Needs more work on the margin and frame sizing to ensure description doesn't get cut off by frames

Mobile Tested.
- Literally broken atm. Will work on soon

**Review by manhellis — APPROVED** [review]
ok yolo

**Pull request merged**
